### ISSUE TITLE
add _version in the output

### ISSUE THREAD

**Issue by leechuen** [jprante/elasticsearch-csv#15]
How to add _version in the output? Query below does not return _version of the doc:

GET /_search_csv?with_id&with_index&keys=_id,_version,_timestamp,fielda&size=10
{
    "fields" : [ "_source","_version","_timestamp"]
  ,"query": {
    "match_all": {}
  }
}

**Comment by jprante** [comment]
The meta field `_version` is not available in search results.

**Comment by jprante** [comment]
You need to set `version` flag in query.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-version.html

**Comment by leechuen** [comment]
I did try to use "version"=true.

 "_version" is returned when I run this query.
GET /_search?
{
"version": true    
,"fields" : [ "_source","_timestamp"]
,"query": {
"match_all": {}
}
} 

But, when I use _search_csv, _version is not returned.
GET /_search_csv?with_id&with_index&keys=_id,_version,_timestamp&size=10
{
"version": true    
,"fields" : [ "_source","_timestamp","_version"]
,"query": {
"match_all": {}
}
}

**Comment by jprante** [comment]
As said, you must use `"version": true` in the query.

```
GET /_search_csv?with_id&with_index&keys=_id,_version,_timestamp&size=10
{
  "fields" : [ "_source","_timestamp","_version"],
  "query": {
      "version": true,
      "match_all": {}
  }
}
```

**Comment by leechuen** [comment]
The sample that I have given above is already with "version": true.

Recap the same statement that I have given above. The _version is not returned when using _search_csv.

GET /_search_csv?with_id&with_index&keys=_id,_version,_timestamp&size=10
{
"version": true
,"fields" : [ "_source","_timestamp","_version"]
,"query": {
"match_all": {}
}
}

**Comment by jprante** [comment]
You did not set `version: true` in the query. Please study carefully, you set it at the wrong place.

**Comment by leechuen** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-version.html is showing "version": true OUTSIDE of the the query. 

The query that you have given, which has "version": true in the query returns error.

Query that you have given:
GET /_search_csv?with_id&with_index&keys=_id,_version,_timestamp&size=10
{
  "fields" : [ "_source","_timestamp","_version"],
  "query": {
      "version": true,
      "match_all": {}
  }
}

Output:
Parse Failure [Failed to parse source [{\n  \"fields\" : [ \"_source\",\"_timestamp\",\"_version\"],\n  \"query\": {\n      \"version\": true,\n      \"match_all\": {}\n  }\n}\n]]]; nested: QueryParsingException[[quote3] [_na] query malformed, no field after start_object];

**Comment by jprante** [comment]
I stand corrected. Sorry. You are right.

Version 1.7.2.1 is just released. You have to add a `with_version=true` HTTP GET parameter, then it should work.

**Comment by leechuen** [comment]
1.7.2.1 is working. Thanks.
