### ISSUE TITLE
Only saves as "_search_csv" on all major browsers

### ISSUE THREAD

**Issue by moonlitdelight** [jprante/elasticsearch-csv#6]
Hi @jprante, is it meant to save as _search_csv all the time? Thank you.

**Comment by jprante** [comment]
Plugins are not meant for browser access. Use curl -o option for filename.

**Comment by moonlitdelight** [comment]
When I read that "it's just like _search", I immediately thought it can be used as how I use _search. I make GET requests to ES using _search RESTful API.

**Comment by jprante** [comment]
Exactly. How do you save in a browser using _search?

**Comment by yusufcan141** [comment]
Hello, how can i get _parent or _id metafields using search_csv because when i put fields:[] in request body it gets nullpointerexception.

**Comment by jprante** [comment]
@yusufcan141 I can add this, please open a separate issue for it

**Comment by yusufcan141** [comment]
Hi @jprante thanks for your care. I opened the issue and besides this metadata problem, this plugin exactly solves my problem. When you can add this feature because i need it a bit urgent :) Thanks
