### ISSUE TITLE
Getting Meta Data

### ISSUE THREAD

**Issue by yusufcan141** [jprante/elasticsearch-csv#7]
I can not get meta data like _parent, _id etc. with search_csv.

**Comment by jprante** [comment]
I just released version 1.4.0.1 of the CSV plugin with that features.

**Comment by yusufcan141** [comment]
Thank you so much, it will be very helpful :)

**Comment by yusufcan141** [comment]
Hi @jprante, how can i use these features. I tried like this:

/index/type/_search_csv
{
    "fields":["_parent"]
}

But it gives NullPointerException again.

**Comment by yusufcan141** [comment]
@jprante can you add also with_parent parameter?

**Comment by jprante** [comment]
Please use something like

```
POST /index/type/_search_csv?with_id
{
    "fields" : [ "_parent","_source"],
    "query": {
        "match_all": {
        }
    }
}
```

**Comment by yusufcan141** [comment]
It worked thank you very much :)
