### ISSUE TITLE
Readme install url 404

### ISSUE THREAD

**Issue by apavillet** [jprante/elasticsearch-csv#8]
http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-csv/1.4.0.0/elasticsearch-csv-1.4.0.0-plugin.zip is a 404 right now,

correct url seems to be http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-csv/1.4.0.1/elasticsearch-csv-1.4.0.1-plugin.zip

**Comment by trivoallan** [comment]
+1

**Comment by jprante** [comment]
Fixed, thanks.
